In [1]:
import pandas as pd
import numpy as np

## Data Preperation

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'

In [ ]:
# !wget $data

--2026-09-29 02:52:54--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: 'data.csv'

     0K .......... .......... .......... .......... ..........  3% 1.92M 1s
    50K .......... .......... .......... .......... ..........  6% 2.31M 1s
   100K .......... .......... .......... .......... .......... 10% 3.25M 1s
   150K .......... .......... .......... .......... .......... 13% 2.28M 1s
   200K .......... .......... .......... .......... .......... 17% 1.72M 1s
   250K .......... .......... .......... .......... .......... 20% 3.50M 0s
   300K .......... .......... .......... .......... .......... 24% 3.89M 0s
   350K .......... .......... .......... .......... .......... 27% 2.38M 0s
   400K .......... .......... .......... .......... .......... 31% 2.19M 0s
   450K .......... .......... .......... .......... .......... 34% 2.36M 0s
   500K .......... .......... .......... .......... .......... 38% 2.22M 0s
   550K .......... .......... .......... .......... .......... 41% 2.91M 0s
   600K .......... .......... .......... .......... .......... 45% 1.98M 0s
   650K .......... .......... .......... .......... .......... 48% 7.12M 0s
   700K .......... .......... .......... .......... .......... 52% 2.16M 0s
   750K .......... .......... .......... .......... .......... 55% 1.82M 0s
   800K .......... .......... .......... .......... .......... 58% 2.19M 0s
   850K .......... .......... .......... .......... .......... 62% 2.21M 0s
   900K .......... .......... .......... .......... .......... 65% 2.94M 0s
   950K .......... .......... .......... .......... .......... 69% 4.25M 0s
  1000K .......... .......... .......... .......... .......... 72% 2.25M 0s
  1050K .......... .......... .......... .......... .......... 76% 2.55M 0s
  1100K .......... .......... .......... .......... .......... 79% 3.24M 0s
  1150K .......... .......... .......... .......... .......... 83% 2.82M 0s
  1200K .......... .......... .......... .......... .......... 86% 1.90M 0s
  1250K .......... .......... .......... .......... .......... 90% 2.14M 0s
  1300K .......... .......... .......... .......... .......... 93% 4.81M 0s
  1350K .......... .......... .......... .......... .......... 97% 1.91M 0s
  1400K .......... .......... .......... ..........           100% 4.34M=0.6s

2026-09-29 02:52:55 (2.51 MB/s) - 'data.csv' saved [1475504/1475504]

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [6]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [7]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500