In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [ ]:
# !wget $data -O data-week-3.csv

--2026-10-04 10:49:33--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... failed: Unknown error.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: 'data-week-3.csv'

     0K .......... .......... .......... .......... ..........  5% 1.66M 1s
    50K .......... .......... .......... .......... .......... 10% 2.32M 0s
   100K .......... .......... .......... .......... .......... 15% 9.45M 0s
   150K .......... .......... .......... .......... .......... 20% 2.20M 0s
   200K .......... .......... .......... .......... .......... 26% 1.99M 0s
   250K .......... .......... .......... .......... .......... 31% 3.40M 0s
   300K .......... .......... .......... .......... .......... 36% 4.37M 0s
   350K .......... .......... .......... .......... .......... 41% 2.03M 0s
   400K .......... .......... .......... .......... .......... 47% 2.01M 0s
   450K .......... .......... .......... .......... .......... 52% 2.85M 0s
   500K .......... .......... .......... .......... .......... 57% 3.68M 0s
   550K .......... .......... .......... .......... .......... 62% 2.25M 0s
   600K .......... .......... .......... .......... .......... 68% 2.43M 0s
   650K .......... .......... .......... .......... .......... 73% 3.96M 0s
   700K .......... .......... .......... .......... .......... 78% 2.07M 0s
   750K .......... .......... .......... .......... .......... 83% 2.17M 0s
   800K .......... .......... .......... .......... .......... 89% 1.52M 0s
   850K .......... .......... .......... .......... .......... 94% 9.73M 0s
   900K .......... .......... .......... .......... .......... 99% 2.42M 0s
   950K ....                                                  100% 87.6G=0.4s

2026-10-04 10:49:55 (2.56 MB/s) - 'data-week-3.csv' saved [977501/977501]

In [4]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [6]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

In [7]:
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [11]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [13]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [14]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [16]:
tc.isnull().sum()

np.int64(11)

In [20]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid totalcharges
488   4472-lvygi            _
753   3115-czmzd            _
936   5709-lvoeq            _
1082  4367-nuyao            _
1340  1371-dwpaz            _
3331  7644-omvmy            _
3826  3213-vvolg            _
4380  2520-sgtta            _
5218  2923-arzlg            _
6670  4075-wkniu            _
6754  2775-sefee            _

In [21]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')

In [22]:
df.totalcharges = df.totalcharges.fillna(0)

In [23]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-lvygi           0.0
753   3115-czmzd           0.0
936   5709-lvoeq           0.0
1082  4367-nuyao           0.0
1340  1371-dwpaz           0.0
3331  7644-omvmy           0.0
3826  3213-vvolg           0.0
4380  2520-sgtta           0.0
5218  2923-arzlg           0.0
6670  4075-wkniu           0.0
6754  2775-sefee           0.0

In [25]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: str

In [26]:
df.churn = (df.churn == 'yes').astype(int)

## Setting up the Validation Framework

In [28]:
from sklearn.model_selection import train_test_split

In [30]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [31]:
len(df_full_train), len(df_test)

(5634, 1409)

In [32]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [33]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [36]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [37]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [38]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

## Exploratory Data Analysis

In [39]:
df_full_train = df_full_train.reset_index(drop=True)

In [40]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64